export const staticAuth = {
  fetching: false,
  fetched: true,
  token: "b03f904a45843d832720e1ead56705c45ac9463a",
  expiresIn: "216000",
  createdAt: 1609754223,
  user: {
    roles: [
      {
        id: 4,
        function: "",
        type: "LEGAL_REPRESENTATIVE",
        typeStatus: "MANAGER",
        validated: false,
        internal: false,
        createdAt: {
          date: "2017-07-24 11:14:12.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        updatedAt: {
          date: "2018-01-25 11:38:57.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        organization: {
          id: 4,
          uen: "0446086370",
          name: "DEG & PARTNERS CONSULTING COMPANY",
          abbreviation: "Deg & Partners",
          avatarWebPath:
            "storage/media/IMAGE/5399/AVATAR_2dac1051cb408f0778edb93fbf8009067d7e9d28.png",
          avatarUrl:
            "https://s3.tamtam.pro/local/storage/media/IMAGE/5399/AVATAR_2dac1051cb408f0778edb93fbf8009067d7e9d28.png",
          btbPreferences: {
            authorizations: [
              { role: "MANAGER", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
              {
                role: "OFFICIAL",
                auth: [
                  "approver",
                  "inbox_viewer",
                  "outbox_viewer",
                  "handle_filter_document_task",
                ],
              },
            ],
          },
          directoryActivated: 1,
          dirPreferences: {
            btbEmail: "emmanuel.degreve@degandpartners.com",
            appliedChannelsStatus: [
              {
                id: "BILLTOBOX_INIT_ID",
                name: "billtobox",
                status: "deactivated",
              },
              {
                id: "BILLTOBOXFILES_INIT_ID",
                name: "billtoboxfiles",
                status: "activated",
              },
            ],
          },
          directBilling: true,
          blogActivated: 1,
          mediaActivated: 1,
          forumActivated: 1,
          webtoolsActivated: 1,
          eventActivated: 1,
          paymentActivated: 0,
          dataActivated: 0,
          surveyActivated: 1,
          fluxActivated: 1,
          chatActivated: 1,
          socialNetworks: {
            twitter: {
              624465904: {
                id: "624465904",
                username: "DegandPartners",
                profile_picture:
                  "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69_normal.jpeg",
                profile_picture_original:
                  "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69.jpeg",
                profile_banner:
                  "https://pbs.twimg.com/profile_banners/624465904/1421767061/600x200",
                accesstoken: {
                  oauth_token:
                    "624465904-LHB2jXz5oCm3KDaH0NNkUbmvHTKFjVKzokVgQ554",
                  oauth_token_secret:
                    "i6sJKCHIFpI7o8HOhRL1p4pg9QYKT8vP7foQgrozsUMQy",
                },
              },
            },
          },
          emailingPreferences: {
            cs_app_scope: "EXTRA_CROSS",
            cs_default_scope: "EXTRA_CROSS",
          },
          emailingTestingPreferences: {
            approversEmailsIds: [],
            autoSend: false,
            mandatoryTest: false,
            minApprover: 0,
          },
          emailingActivated: 1,
          appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
          mediaPreferences: {
            languages: "FR,NL",
            generalTypes: "VIDEO,PDF,PPT",
            publicProfile: "1",
            defaultData: "{}",
          },
          hubPreferences: {
            layout_settings: [
              { sectionId: "event", order: 2, enabled: true },
              { sectionId: "forum", order: 4, enabled: false },
              { sectionId: "media", order: 3, enabled: true },
              { sectionId: "blog", order: 1, enabled: true },
            ],
            drawers: [
              {
                app: "BLOG",
                label: "Blog",
                url: "http://local.blog.tamtam.pro",
                enabled: true,
              },
              {
                app: "EVENT",
                label: "Event",
                url: "http://local.event.tamtam.pro",
                enabled: true,
              },
              {
                app: "MEDIA",
                label: "Media",
                url: "http://local.media.tamtam.pro:3333",
                enabled: true,
              },
              {
                app: "FORUM",
                label: "Forum",
                url: "http://local.forum.tamtam.pro:3001",
                enabled: true,
              },
            ],
          },
          smsCredit: 0,
          profitMargin: 0,
          defaultMemberAuthorisationMode: "",
          defaultProspectAuthorisationMode: "",
          gdprAlertEnabled: 0,
          csGeneralScope: "EXTRA_CROSS",
          portalClientActivated: 1,
          portalOfficialActivated: 1,
          organizationSettingsId: 4,
          appsState: [
            {
              code: "blog",
              name: { fr: "Blog", en: "Blog", nl: "Blog" },
              url: "https://blog.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/blog.png",
              activated: true,
            },
            {
              code: "media",
              name: { fr: "Media", en: "Media", nl: "Media" },
              url: "https://media.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/media.png",
              activated: true,
            },
            {
              code: "forum",
              name: { fr: "Forum", en: "Forum", nl: "Forum" },
              url: "https://forum.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/forum.png",
              activated: true,
            },
            {
              code: "emailing",
              name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
              url: "https://sending.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
              activated: true,
            },
            {
              code: "ebox",
              name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
              url: "https://sending.rc2.tamtam.pro/e_box",
              icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
              activated: true,
            },
            {
              code: "sms",
              name: { fr: "SMS", en: "SMS", nl: "SMS" },
              url: "https://sending.rc2.tamtam.pro/smsCampaigns",
              icon: "https://s3.tamtam.pro/v2/apps/sms.png",
              activated: true,
            },
            {
              code: "talk",
              name: { fr: "Talk", en: "Talk", nl: "Talk" },
              url: "https://talk.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/talk.png",
              activated: true,
            },
            {
              code: "data",
              name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
              url: "https://accounting.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
              activated: false,
            },
            {
              code: "webtools",
              name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
              url: "https://webtool.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
              activated: true,
            },
            {
              code: "survey",
              name: { fr: "Survey", en: "Survey", nl: "Survey" },
              url: "https://survey.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/survey.png",
              activated: true,
            },
            {
              code: "event",
              name: { fr: "Event", en: "Event", nl: "Event" },
              url: "https://event.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/event.png",
              activated: true,
            },
            {
              code: "directory",
              name: {
                fr: "Directory (HQ)",
                en: "Directory (HQ)",
                nl: "Directory (HQ)",
              },
              url: "https://rc2.tamtam.pro/folders",
              icon: "https://s3.tamtam.pro/v2/apps/directory.png",
              activated: true,
            },
            {
              code: "payment",
              name: { fr: "Payment", en: "Payment", nl: "Payment" },
              url: "https://payment.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/payment.png",
              activated: false,
            },
            {
              code: "portal",
              name: { fr: "Portal", en: "Portal", nl: "Portal" },
              url: "https://portal.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/portal.png",
              activated: true,
            },
          ],
          startDate: null,
        },
      },
      {
        id: 37,
        function: "",
        type: "LEGAL_REPRESENTATIVE",
        typeStatus: "ADMIN",
        validated: false,
        internal: false,
        createdAt: {
          date: "2017-09-11 20:22:13.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        updatedAt: {
          date: "2017-09-11 20:22:13.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        organization: {
          id: 9,
          uen: "0899167234",
          name: "Forum For The Future",
          abbreviation: "F.F.F.",
          avatarWebPath:
            "storage/media/IMAGE/5400/AVATAR_74ad9ed232db222831d9dd2cb0bae95fcb64eeb0.png",
          avatarUrl:
            "https://s3.tamtam.pro/local/storage/media/IMAGE/5400/AVATAR_74ad9ed232db222831d9dd2cb0bae95fcb64eeb0.png",
          btbPreferences: {
            authorizations: [
              { role: "MANAGER", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
              {
                role: "OFFICIAL",
                auth: [
                  "approver",
                  "inbox_viewer",
                  "outbox_viewer",
                  "handle_filter_document_task",
                ],
              },
            ],
          },
          directoryActivated: 0,
          dirPreferences: { btbEmail: "bruno.delescaille@degandpartners.com" },
          directBilling: true,
          blogActivated: 1,
          mediaActivated: 1,
          forumActivated: 1,
          webtoolsActivated: 0,
          eventActivated: 1,
          paymentActivated: 0,
          dataActivated: 0,
          surveyActivated: 1,
          fluxActivated: 1,
          chatActivated: 1,
          socialNetworks: [],
          emailingPreferences: {
            from_email: "info@forumforthefuture.be",
            base_url: "http://tamtam.pro/emails2017",
            from_name: "ForumForTheFuture",
            cs_app_scope: "EXTRA_CROSS",
            cs_default_scope: "EXTRA_CROSS",
          },
          emailingActivated: 1,
          appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
          mediaPreferences: {
            languages: "FR,NL,EN",
            generalTypes: "VIDEO,PDF,PPT,IMAGE",
            publicProfile: "1",
            defaultData: "{}",
          },
          hubPreferences: {
            layout_settings: [
              { sectionId: "event", order: 1, enabled: true },
              { sectionId: "media", order: 2, enabled: true },
              { sectionId: "blog", order: 3, enabled: true },
              { sectionId: "forum", order: 4, enabled: false },
            ],
            drawers: [
              {
                app: "BLOG",
                label: "Blog",
                url: "https://blog.rc2.forumforthefuture.be",
                enabled: true,
              },
              {
                app: "EVENT",
                label: "Event",
                url: "https://event.rc2.tamtam.pro/fr/events/select",
                enabled: true,
              },
              {
                app: "MEDIA",
                label: "Media",
                url:
                  "https://media.rc2.tamtam.pro/community/forum-for-the-future/9",
                enabled: true,
              },
              {
                app: "FORUM",
                label: "Forum",
                url: "https://stackoverflow.com/",
                enabled: true,
              },
            ],
          },
          smsCredit: 0,
          profitMargin: 0,
          defaultMemberAuthorisationMode: "",
          defaultProspectAuthorisationMode: "",
          gdprAlertEnabled: 0,
          portalClientActivated: 0,
          portalOfficialActivated: 0,
          organizationSettingsId: 7,
          appsState: [
            {
              code: "blog",
              name: { fr: "Blog", en: "Blog", nl: "Blog" },
              url: "https://blog.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/blog.png",
              activated: true,
            },
            {
              code: "media",
              name: { fr: "Media", en: "Media", nl: "Media" },
              url: "https://media.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/media.png",
              activated: true,
            },
            {
              code: "forum",
              name: { fr: "Forum", en: "Forum", nl: "Forum" },
              url: "https://forum.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/forum.png",
              activated: true,
            },
            {
              code: "emailing",
              name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
              url: "https://sending.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
              activated: true,
            },
            {
              code: "ebox",
              name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
              url: "https://sending.rc2.tamtam.pro/e_box",
              icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
              activated: true,
            },
            {
              code: "sms",
              name: { fr: "SMS", en: "SMS", nl: "SMS" },
              url: "https://sending.rc2.tamtam.pro/smsCampaigns",
              icon: "https://s3.tamtam.pro/v2/apps/sms.png",
              activated: true,
            },
            {
              code: "talk",
              name: { fr: "Talk", en: "Talk", nl: "Talk" },
              url: "https://talk.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/talk.png",
              activated: true,
            },
            {
              code: "data",
              name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
              url: "https://accounting.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
              activated: false,
            },
            {
              code: "webtools",
              name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
              url: "https://webtool.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
              activated: false,
            },
            {
              code: "survey",
              name: { fr: "Survey", en: "Survey", nl: "Survey" },
              url: "https://survey.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/survey.png",
              activated: true,
            },
            {
              code: "event",
              name: { fr: "Event", en: "Event", nl: "Event" },
              url: "https://event.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/event.png",
              activated: true,
            },
            {
              code: "directory",
              name: {
                fr: "Directory (HQ)",
                en: "Directory (HQ)",
                nl: "Directory (HQ)",
              },
              url: "https://rc2.tamtam.pro/folders",
              icon: "https://s3.tamtam.pro/v2/apps/directory.png",
              activated: false,
            },
            {
              code: "payment",
              name: { fr: "Payment", en: "Payment", nl: "Payment" },
              url: "https://payment.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/payment.png",
              activated: false,
            },
            {
              code: "portal",
              name: { fr: "Portal", en: "Portal", nl: "Portal" },
              url: "https://portal.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/portal.png",
              activated: false,
            },
          ],
          startDate: null,
          hasFiduciariesAdmin: true,
        },
      },
      {
        id: 133,
        function: "",
        type: "LEGAL_REPRESENTATIVE",
        typeStatus: "ADMIN",
        validated: false,
        internal: false,
        createdAt: {
          date: "2017-12-12 10:51:15.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        updatedAt: {
          date: "2017-12-12 10:51:15.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        organization: {
          id: 76,
          uen: "0446086371",
          name: "Tamtam Pro",
          abbreviation: "",
          btbPreferences: {
            authorizations: [
              { role: "MANAGER", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
              {
                role: "OFFICIAL",
                auth: [
                  "approver",
                  "inbox_viewer",
                  "outbox_viewer",
                  "handle_filter_document_task",
                ],
              },
            ],
          },
          directoryActivated: 0,
          dirPreferences: { btbEmail: "elkenziamine@gmail.com" },
          directBilling: true,
          blogActivated: 1,
          mediaActivated: 0,
          forumActivated: 0,
          webtoolsActivated: 0,
          eventActivated: 0,
          paymentActivated: 0,
          dataActivated: 0,
          surveyActivated: 0,
          fluxActivated: 1,
          chatActivated: 1,
          socialNetworks: [],
          emailingActivated: 0,
          appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
          smsCredit: 0,
          profitMargin: 0,
          gdprAlertEnabled: 0,
          portalClientActivated: 0,
          portalOfficialActivated: 0,
          organizationSettingsId: 74,
          appsState: [
            {
              code: "blog",
              name: { fr: "Blog", en: "Blog", nl: "Blog" },
              url: "https://blog.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/blog.png",
              activated: true,
            },
            {
              code: "media",
              name: { fr: "Media", en: "Media", nl: "Media" },
              url: "https://media.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/media.png",
              activated: false,
            },
            {
              code: "forum",
              name: { fr: "Forum", en: "Forum", nl: "Forum" },
              url: "https://forum.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/forum.png",
              activated: false,
            },
            {
              code: "emailing",
              name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
              url: "https://sending.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
              activated: false,
            },
            {
              code: "ebox",
              name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
              url: "https://sending.rc2.tamtam.pro/e_box",
              icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
              activated: true,
            },
            {
              code: "sms",
              name: { fr: "SMS", en: "SMS", nl: "SMS" },
              url: "https://sending.rc2.tamtam.pro/smsCampaigns",
              icon: "https://s3.tamtam.pro/v2/apps/sms.png",
              activated: false,
            },
            {
              code: "talk",
              name: { fr: "Talk", en: "Talk", nl: "Talk" },
              url: "https://talk.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/talk.png",
              activated: true,
            },
            {
              code: "data",
              name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
              url: "https://accounting.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
              activated: false,
            },
            {
              code: "webtools",
              name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
              url: "https://webtool.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
              activated: false,
            },
            {
              code: "survey",
              name: { fr: "Survey", en: "Survey", nl: "Survey" },
              url: "https://survey.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/survey.png",
              activated: false,
            },
            {
              code: "event",
              name: { fr: "Event", en: "Event", nl: "Event" },
              url: "https://event.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/event.png",
              activated: false,
            },
            {
              code: "directory",
              name: {
                fr: "Directory (HQ)",
                en: "Directory (HQ)",
                nl: "Directory (HQ)",
              },
              url: "https://rc2.tamtam.pro/folders",
              icon: "https://s3.tamtam.pro/v2/apps/directory.png",
              activated: false,
            },
            {
              code: "payment",
              name: { fr: "Payment", en: "Payment", nl: "Payment" },
              url: "https://payment.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/payment.png",
              activated: false,
            },
            {
              code: "portal",
              name: { fr: "Portal", en: "Portal", nl: "Portal" },
              url: "https://portal.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/portal.png",
              activated: false,
            },
          ],
          startDate: null,
        },
      },
      {
        id: 157,
        function: "",
        type: "LEGAL_REPRESENTATIVE",
        typeStatus: "ADMIN",
        validated: false,
        internal: false,
        createdAt: {
          date: "2018-02-27 10:27:58.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        updatedAt: {
          date: "2018-02-27 10:27:58.000000",
          timezone_type: 3,
          timezone: "Africa/Casablanca",
        },
        organization: {
          id: 83,
          uen: "0000002018",
          name: "Tamtam",
          abbreviation: "",
          btbPreferences: {
            authorizations: [
              { role: "MANAGER", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
              { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
              {
                role: "OFFICIAL",
                auth: [
                  "approver",
                  "inbox_viewer",
                  "outbox_viewer",
                  "handle_filter_document_task",
                ],
              },
            ],
          },
          directoryActivated: 0,
          dirPreferences: { btbEmail: "ramrami.mohamed.4@gmail.com" },
          directBilling: true,
          blogActivated: 0,
          mediaActivated: 0,
          forumActivated: 0,
          webtoolsActivated: 0,
          eventActivated: 0,
          paymentActivated: 0,
          dataActivated: 0,
          surveyActivated: 0,
          fluxActivated: 0,
          chatActivated: 1,
          socialNetworks: [],
          emailingActivated: 0,
          appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
          smsCredit: 0,
          profitMargin: 0,
          gdprAlertEnabled: 0,
          portalClientActivated: 0,
          portalOfficialActivated: 0,
          organizationSettingsId: 81,
          appsState: [
            {
              code: "blog",
              name: { fr: "Blog", en: "Blog", nl: "Blog" },
              url: "https://blog.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/blog.png",
              activated: false,
            },
            {
              code: "media",
              name: { fr: "Media", en: "Media", nl: "Media" },
              url: "https://media.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/media.png",
              activated: false,
            },
            {
              code: "forum",
              name: { fr: "Forum", en: "Forum", nl: "Forum" },
              url: "https://forum.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/forum.png",
              activated: false,
            },
            {
              code: "emailing",
              name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
              url: "https://sending.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
              activated: false,
            },
            {
              code: "ebox",
              name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
              url: "https://sending.rc2.tamtam.pro/e_box",
              icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
              activated: true,
            },
            {
              code: "sms",
              name: { fr: "SMS", en: "SMS", nl: "SMS" },
              url: "https://sending.rc2.tamtam.pro/smsCampaigns",
              icon: "https://s3.tamtam.pro/v2/apps/sms.png",
              activated: false,
            },
            {
              code: "talk",
              name: { fr: "Talk", en: "Talk", nl: "Talk" },
              url: "https://talk.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/talk.png",
              activated: true,
            },
            {
              code: "data",
              name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
              url: "https://accounting.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
              activated: false,
            },
            {
              code: "webtools",
              name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
              url: "https://webtool.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
              activated: false,
            },
            {
              code: "survey",
              name: { fr: "Survey", en: "Survey", nl: "Survey" },
              url: "https://survey.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/survey.png",
              activated: false,
            },
            {
              code: "event",
              name: { fr: "Event", en: "Event", nl: "Event" },
              url: "https://event.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/event.png",
              activated: false,
            },
            {
              code: "directory",
              name: {
                fr: "Directory (HQ)",
                en: "Directory (HQ)",
                nl: "Directory (HQ)",
              },
              url: "https://rc2.tamtam.pro/folders",
              icon: "https://s3.tamtam.pro/v2/apps/directory.png",
              activated: false,
            },
            {
              code: "payment",
              name: { fr: "Payment", en: "Payment", nl: "Payment" },
              url: "https://payment.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/payment.png",
              activated: false,
            },
            {
              code: "portal",
              name: { fr: "Portal", en: "Portal", nl: "Portal" },
              url: "https://portal.rc2.tamtam.pro/",
              icon: "https://s3.tamtam.pro/v2/apps/portal.png",
              activated: false,
            },
          ],
          startDate: null,
        },
      },
    ],
    enabled: true,
    firstName: "Emmanuel",
    lastName: "Degrève",
    language: "fr",
    type: "ADMIN",
    status: "CREATED",
    situation: "active",
    institute: "",
    numeroAgreation: "",
    gender: "MALE",
    description: "",
    title: "Monsieur",
    salutation: "Cher confrère",
    function: "Owner",
    isSecure: true,
    hasAgreedTerms: true,
    id: 8650,
    mainEmail: "emmanuel.degreve@degandpartners.com",
    mainPhone: "+32486210211",
    userMobilePhone: "",
    role: {
      id: 4,
      function: "",
      type: "LEGAL_REPRESENTATIVE",
      typeStatus: "MANAGER",
      validated: false,
      internal: false,
      createdAt: {
        date: "2017-07-24 11:14:12.000000",
        timezone_type: 3,
        timezone: "Africa/Casablanca",
      },
      updatedAt: {
        date: "2018-01-25 11:38:57.000000",
        timezone_type: 3,
        timezone: "Africa/Casablanca",
      },
      organization: {
        id: 4,
        uen: "0446086370",
        name: "DEG & PARTNERS CONSULTING COMPANY",
        abbreviation: "Deg & Partners",
        avatarWebPath:
          "storage/media/IMAGE/5399/AVATAR_2dac1051cb408f0778edb93fbf8009067d7e9d28.png",
        avatarUrl:
          "https://s3.tamtam.pro/local/storage/media/IMAGE/5399/AVATAR_2dac1051cb408f0778edb93fbf8009067d7e9d28.png",
        btbPreferences: {
          authorizations: [
            { role: "MANAGER", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
            {
              role: "OFFICIAL",
              auth: [
                "approver",
                "inbox_viewer",
                "outbox_viewer",
                "handle_filter_document_task",
              ],
            },
          ],
        },
        directoryActivated: 1,
        dirPreferences: {
          btbEmail: "emmanuel.degreve@degandpartners.com",
          appliedChannelsStatus: [
            {
              id: "BILLTOBOX_INIT_ID",
              name: "billtobox",
              status: "deactivated",
            },
            {
              id: "BILLTOBOXFILES_INIT_ID",
              name: "billtoboxfiles",
              status: "activated",
            },
          ],
        },
        directBilling: true,
        blogActivated: 1,
        mediaActivated: 1,
        forumActivated: 1,
        webtoolsActivated: 1,
        eventActivated: 1,
        paymentActivated: 0,
        dataActivated: 0,
        surveyActivated: 1,
        fluxActivated: 1,
        chatActivated: 1,
        socialNetworks: {
          twitter: {
            624465904: {
              id: "624465904",
              username: "DegandPartners",
              profile_picture:
                "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69_normal.jpeg",
              profile_picture_original:
                "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69.jpeg",
              profile_banner:
                "https://pbs.twimg.com/profile_banners/624465904/1421767061/600x200",
              accesstoken: {
                oauth_token:
                  "624465904-LHB2jXz5oCm3KDaH0NNkUbmvHTKFjVKzokVgQ554",
                oauth_token_secret:
                  "i6sJKCHIFpI7o8HOhRL1p4pg9QYKT8vP7foQgrozsUMQy",
              },
            },
          },
        },
        emailingPreferences: {
          cs_app_scope: "EXTRA_CROSS",
          cs_default_scope: "EXTRA_CROSS",
        },
        emailingTestingPreferences: {
          approversEmailsIds: [],
          autoSend: false,
          mandatoryTest: false,
          minApprover: 0,
        },
        emailingActivated: 1,
        appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
        mediaPreferences: {
          languages: "FR,NL",
          generalTypes: "VIDEO,PDF,PPT",
          publicProfile: "1",
          defaultData: "{}",
        },
        hubPreferences: {
          layout_settings: [
            { sectionId: "event", order: 2, enabled: true },
            { sectionId: "forum", order: 4, enabled: false },
            { sectionId: "media", order: 3, enabled: true },
            { sectionId: "blog", order: 1, enabled: true },
          ],
          drawers: [
            {
              app: "BLOG",
              label: "Blog",
              url: "http://local.blog.tamtam.pro",
              enabled: true,
            },
            {
              app: "EVENT",
              label: "Event",
              url: "http://local.event.tamtam.pro",
              enabled: true,
            },
            {
              app: "MEDIA",
              label: "Media",
              url: "http://local.media.tamtam.pro:3333",
              enabled: true,
            },
            {
              app: "FORUM",
              label: "Forum",
              url: "http://local.forum.tamtam.pro:3001",
              enabled: true,
            },
          ],
        },
        smsCredit: 0,
        profitMargin: 0,
        defaultMemberAuthorisationMode: "",
        defaultProspectAuthorisationMode: "",
        gdprAlertEnabled: 0,
        csGeneralScope: "EXTRA_CROSS",
        portalClientActivated: 1,
        portalOfficialActivated: 1,
        organizationSettingsId: 4,
        appsState: [
          {
            code: "blog",
            name: { fr: "Blog", en: "Blog", nl: "Blog" },
            url: "https://blog.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/blog.png",
            activated: true,
          },
          {
            code: "media",
            name: { fr: "Media", en: "Media", nl: "Media" },
            url: "https://media.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/media.png",
            activated: true,
          },
          {
            code: "forum",
            name: { fr: "Forum", en: "Forum", nl: "Forum" },
            url: "https://forum.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/forum.png",
            activated: true,
          },
          {
            code: "emailing",
            name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
            url: "https://sending.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
            activated: true,
          },
          {
            code: "ebox",
            name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
            url: "https://sending.rc2.tamtam.pro/e_box",
            icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
            activated: true,
          },
          {
            code: "sms",
            name: { fr: "SMS", en: "SMS", nl: "SMS" },
            url: "https://sending.rc2.tamtam.pro/smsCampaigns",
            icon: "https://s3.tamtam.pro/v2/apps/sms.png",
            activated: true,
          },
          {
            code: "talk",
            name: { fr: "Talk", en: "Talk", nl: "Talk" },
            url: "https://talk.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/talk.png",
            activated: true,
          },
          {
            code: "data",
            name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
            url: "https://accounting.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
            activated: false,
          },
          {
            code: "webtools",
            name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
            url: "https://webtool.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
            activated: true,
          },
          {
            code: "survey",
            name: { fr: "Survey", en: "Survey", nl: "Survey" },
            url: "https://survey.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/survey.png",
            activated: true,
          },
          {
            code: "event",
            name: { fr: "Event", en: "Event", nl: "Event" },
            url: "https://event.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/event.png",
            activated: true,
          },
          {
            code: "directory",
            name: {
              fr: "Directory (HQ)",
              en: "Directory (HQ)",
              nl: "Directory (HQ)",
            },
            url: "https://rc2.tamtam.pro/folders",
            icon: "https://s3.tamtam.pro/v2/apps/directory.png",
            activated: true,
          },
          {
            code: "payment",
            name: { fr: "Payment", en: "Payment", nl: "Payment" },
            url: "https://payment.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/payment.png",
            activated: false,
          },
          {
            code: "portal",
            name: { fr: "Portal", en: "Portal", nl: "Portal" },
            url: "https://portal.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/portal.png",
            activated: true,
          },
        ],
        startDate: null,
      },
    },
    avatar:
      "storage/media/IMAGE/31/AVATAR_24679fb9c4c3bb5fe4a7850e99a3c5d070f8672f.png",
    avatarUrl:
      "https://s3.tamtam.pro/local/storage/media/IMAGE/31/AVATAR_24679fb9c4c3bb5fe4a7850e99a3c5d070f8672f.png",
    cover:
      "storage/media/IMAGE/32/COVER_48e115db3e7dd745175282dba406f35819584d97.jpeg",
    coverUrl:
      "https://s3.tamtam.pro/local/storage/media/IMAGE/32/COVER_48e115db3e7dd745175282dba406f35819584d97.jpeg",
    communities: [
      {
        id: 4,
        uen: "0446086370",
        name: "DEG & PARTNERS CONSULTING COMPANY",
        abbreviation: "Deg & Partners",
        avatarWebPath:
          "storage/media/IMAGE/5399/AVATAR_2dac1051cb408f0778edb93fbf8009067d7e9d28.png",
        avatarUrl:
          "https://s3.tamtam.pro/local/storage/media/IMAGE/5399/AVATAR_2dac1051cb408f0778edb93fbf8009067d7e9d28.png",
        btbPreferences: {
          authorizations: [
            { role: "MANAGER", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
            {
              role: "OFFICIAL",
              auth: [
                "approver",
                "inbox_viewer",
                "outbox_viewer",
                "handle_filter_document_task",
              ],
            },
          ],
        },
        directoryActivated: 1,
        dirPreferences: {
          btbEmail: "emmanuel.degreve@degandpartners.com",
          appliedChannelsStatus: [
            {
              id: "BILLTOBOX_INIT_ID",
              name: "billtobox",
              status: "deactivated",
            },
            {
              id: "BILLTOBOXFILES_INIT_ID",
              name: "billtoboxfiles",
              status: "activated",
            },
          ],
        },
        directBilling: true,
        blogActivated: 1,
        mediaActivated: 1,
        forumActivated: 1,
        webtoolsActivated: 1,
        eventActivated: 1,
        paymentActivated: 0,
        dataActivated: 0,
        surveyActivated: 1,
        fluxActivated: 1,
        chatActivated: 1,
        socialNetworks: {
          twitter: {
            624465904: {
              id: "624465904",
              username: "DegandPartners",
              profile_picture:
                "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69_normal.jpeg",
              profile_picture_original:
                "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69.jpeg",
              profile_banner:
                "https://pbs.twimg.com/profile_banners/624465904/1421767061/600x200",
              accesstoken: {
                oauth_token:
                  "624465904-LHB2jXz5oCm3KDaH0NNkUbmvHTKFjVKzokVgQ554",
                oauth_token_secret:
                  "i6sJKCHIFpI7o8HOhRL1p4pg9QYKT8vP7foQgrozsUMQy",
              },
            },
          },
        },
        emailingPreferences: {
          cs_app_scope: "EXTRA_CROSS",
          cs_default_scope: "EXTRA_CROSS",
        },
        emailingTestingPreferences: {
          approversEmailsIds: [],
          autoSend: false,
          mandatoryTest: false,
          minApprover: 0,
        },
        emailingActivated: 1,
        appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
        mediaPreferences: {
          languages: "FR,NL",
          generalTypes: "VIDEO,PDF,PPT",
          publicProfile: "1",
          defaultData: "{}",
        },
        hubPreferences: {
          layout_settings: [
            { sectionId: "event", order: 2, enabled: true },
            { sectionId: "forum", order: 4, enabled: false },
            { sectionId: "media", order: 3, enabled: true },
            { sectionId: "blog", order: 1, enabled: true },
          ],
          drawers: [
            {
              app: "BLOG",
              label: "Blog",
              url: "http://local.blog.tamtam.pro",
              enabled: true,
            },
            {
              app: "EVENT",
              label: "Event",
              url: "http://local.event.tamtam.pro",
              enabled: true,
            },
            {
              app: "MEDIA",
              label: "Media",
              url: "http://local.media.tamtam.pro:3333",
              enabled: true,
            },
            {
              app: "FORUM",
              label: "Forum",
              url: "http://local.forum.tamtam.pro:3001",
              enabled: true,
            },
          ],
        },
        smsCredit: 0,
        profitMargin: 0,
        defaultMemberAuthorisationMode: "",
        defaultProspectAuthorisationMode: "",
        gdprAlertEnabled: 0,
        csGeneralScope: "EXTRA_CROSS",
        portalClientActivated: 1,
        portalOfficialActivated: 1,
        organizationSettingsId: 4,
        appsState: [
          {
            code: "blog",
            name: { fr: "Blog", en: "Blog", nl: "Blog" },
            url: "https://blog.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/blog.png",
            activated: true,
          },
          {
            code: "media",
            name: { fr: "Media", en: "Media", nl: "Media" },
            url: "https://media.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/media.png",
            activated: true,
          },
          {
            code: "forum",
            name: { fr: "Forum", en: "Forum", nl: "Forum" },
            url: "https://forum.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/forum.png",
            activated: true,
          },
          {
            code: "emailing",
            name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
            url: "https://sending.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
            activated: true,
          },
          {
            code: "ebox",
            name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
            url: "https://sending.rc2.tamtam.pro/e_box",
            icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
            activated: true,
          },
          {
            code: "sms",
            name: { fr: "SMS", en: "SMS", nl: "SMS" },
            url: "https://sending.rc2.tamtam.pro/smsCampaigns",
            icon: "https://s3.tamtam.pro/v2/apps/sms.png",
            activated: true,
          },
          {
            code: "talk",
            name: { fr: "Talk", en: "Talk", nl: "Talk" },
            url: "https://talk.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/talk.png",
            activated: true,
          },
          {
            code: "data",
            name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
            url: "https://accounting.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
            activated: false,
          },
          {
            code: "webtools",
            name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
            url: "https://webtool.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
            activated: true,
          },
          {
            code: "survey",
            name: { fr: "Survey", en: "Survey", nl: "Survey" },
            url: "https://survey.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/survey.png",
            activated: true,
          },
          {
            code: "event",
            name: { fr: "Event", en: "Event", nl: "Event" },
            url: "https://event.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/event.png",
            activated: true,
          },
          {
            code: "directory",
            name: {
              fr: "Directory (HQ)",
              en: "Directory (HQ)",
              nl: "Directory (HQ)",
            },
            url: "https://rc2.tamtam.pro/folders",
            icon: "https://s3.tamtam.pro/v2/apps/directory.png",
            activated: true,
          },
          {
            code: "payment",
            name: { fr: "Payment", en: "Payment", nl: "Payment" },
            url: "https://payment.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/payment.png",
            activated: false,
          },
          {
            code: "portal",
            name: { fr: "Portal", en: "Portal", nl: "Portal" },
            url: "https://portal.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/portal.png",
            activated: true,
          },
        ],
        startDate: null,
        url: "deg-and-partners-consulting-company",
        blogs: [
          {
            blogId: 8,
            id: 26,
            role: "CHIEF_EDITOR",
            preferences: {
              allowCreateTags: 1,
              allowedLanguages: ["en", "fr", "nl"],
            },
            mandated: false,
          },
        ],
        mediaSettings: {
          preferences: {
            languages: "FR,NL",
            generalTypes: "VIDEO,PDF,PPT",
            publicProfile: "1",
            defaultData: "{}",
          },
          roles: {
            id: 4,
            preferences: { languages: "FR,EN,NL" },
            imageRole: "CHIEF_EDITOR",
            pdfRole: "CHIEF_EDITOR",
            pptRole: "CHIEF_EDITOR",
            videoRole: "",
          },
        },
      },
      {
        id: 9,
        uen: "0899167234",
        name: "Forum For The Future",
        abbreviation: "F.F.F.",
        avatarWebPath:
          "storage/media/IMAGE/5400/AVATAR_74ad9ed232db222831d9dd2cb0bae95fcb64eeb0.png",
        avatarUrl:
          "https://s3.tamtam.pro/local/storage/media/IMAGE/5400/AVATAR_74ad9ed232db222831d9dd2cb0bae95fcb64eeb0.png",
        btbPreferences: {
          authorizations: [
            { role: "MANAGER", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
            {
              role: "OFFICIAL",
              auth: [
                "approver",
                "inbox_viewer",
                "outbox_viewer",
                "handle_filter_document_task",
              ],
            },
          ],
        },
        directoryActivated: 0,
        dirPreferences: { btbEmail: "bruno.delescaille@degandpartners.com" },
        directBilling: true,
        blogActivated: 1,
        mediaActivated: 1,
        forumActivated: 1,
        webtoolsActivated: 0,
        eventActivated: 1,
        paymentActivated: 0,
        dataActivated: 0,
        surveyActivated: 1,
        fluxActivated: 1,
        chatActivated: 1,
        socialNetworks: [],
        emailingPreferences: {
          from_email: "info@forumforthefuture.be",
          base_url: "http://tamtam.pro/emails2017",
          from_name: "ForumForTheFuture",
          cs_app_scope: "EXTRA_CROSS",
          cs_default_scope: "EXTRA_CROSS",
        },
        emailingActivated: 1,
        appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
        mediaPreferences: {
          languages: "FR,NL,EN",
          generalTypes: "VIDEO,PDF,PPT,IMAGE",
          publicProfile: "1",
          defaultData: "{}",
        },
        hubPreferences: {
          layout_settings: [
            { sectionId: "event", order: 1, enabled: true },
            { sectionId: "media", order: 2, enabled: true },
            { sectionId: "blog", order: 3, enabled: true },
            { sectionId: "forum", order: 4, enabled: false },
          ],
          drawers: [
            {
              app: "BLOG",
              label: "Blog",
              url: "https://blog.rc2.forumforthefuture.be",
              enabled: true,
            },
            {
              app: "EVENT",
              label: "Event",
              url: "https://event.rc2.tamtam.pro/fr/events/select",
              enabled: true,
            },
            {
              app: "MEDIA",
              label: "Media",
              url:
                "https://media.rc2.tamtam.pro/community/forum-for-the-future/9",
              enabled: true,
            },
            {
              app: "FORUM",
              label: "Forum",
              url: "https://stackoverflow.com/",
              enabled: true,
            },
          ],
        },
        smsCredit: 0,
        profitMargin: 0,
        defaultMemberAuthorisationMode: "",
        defaultProspectAuthorisationMode: "",
        gdprAlertEnabled: 0,
        portalClientActivated: 0,
        portalOfficialActivated: 0,
        organizationSettingsId: 7,
        appsState: [
          {
            code: "blog",
            name: { fr: "Blog", en: "Blog", nl: "Blog" },
            url: "https://blog.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/blog.png",
            activated: true,
          },
          {
            code: "media",
            name: { fr: "Media", en: "Media", nl: "Media" },
            url: "https://media.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/media.png",
            activated: true,
          },
          {
            code: "forum",
            name: { fr: "Forum", en: "Forum", nl: "Forum" },
            url: "https://forum.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/forum.png",
            activated: true,
          },
          {
            code: "emailing",
            name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
            url: "https://sending.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
            activated: true,
          },
          {
            code: "ebox",
            name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
            url: "https://sending.rc2.tamtam.pro/e_box",
            icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
            activated: true,
          },
          {
            code: "sms",
            name: { fr: "SMS", en: "SMS", nl: "SMS" },
            url: "https://sending.rc2.tamtam.pro/smsCampaigns",
            icon: "https://s3.tamtam.pro/v2/apps/sms.png",
            activated: true,
          },
          {
            code: "talk",
            name: { fr: "Talk", en: "Talk", nl: "Talk" },
            url: "https://talk.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/talk.png",
            activated: true,
          },
          {
            code: "data",
            name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
            url: "https://accounting.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
            activated: false,
          },
          {
            code: "webtools",
            name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
            url: "https://webtool.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
            activated: false,
          },
          {
            code: "survey",
            name: { fr: "Survey", en: "Survey", nl: "Survey" },
            url: "https://survey.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/survey.png",
            activated: true,
          },
          {
            code: "event",
            name: { fr: "Event", en: "Event", nl: "Event" },
            url: "https://event.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/event.png",
            activated: true,
          },
          {
            code: "directory",
            name: {
              fr: "Directory (HQ)",
              en: "Directory (HQ)",
              nl: "Directory (HQ)",
            },
            url: "https://rc2.tamtam.pro/folders",
            icon: "https://s3.tamtam.pro/v2/apps/directory.png",
            activated: false,
          },
          {
            code: "payment",
            name: { fr: "Payment", en: "Payment", nl: "Payment" },
            url: "https://payment.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/payment.png",
            activated: false,
          },
          {
            code: "portal",
            name: { fr: "Portal", en: "Portal", nl: "Portal" },
            url: "https://portal.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/portal.png",
            activated: false,
          },
        ],
        startDate: null,
        url: "forum-for-the-future",
        hasFiduciariesAdmin: true,
        blogs: [
          {
            blogId: 9,
            id: 31,
            role: "CHIEF_EDITOR",
            preferences: {
              allowCreateTags: 1,
              allowedLanguages: ["en", "fr", "nl"],
            },
            mandated: false,
          },
        ],
        mediaSettings: {
          preferences: {
            languages: "FR,NL,EN",
            generalTypes: "VIDEO,PDF,PPT,IMAGE",
            publicProfile: "1",
            defaultData: "{}",
          },
          roles: {
            id: 1,
            preferences: { languages: "FR,NL,EN" },
            imageRole: "CHIEF_EDITOR",
            pdfRole: "CHIEF_EDITOR",
            pptRole: "CHIEF_EDITOR",
            videoRole: "CHIEF_EDITOR",
          },
        },
      },
      {
        id: 76,
        uen: "0446086371",
        name: "Tamtam Pro",
        abbreviation: "",
        btbPreferences: {
          authorizations: [
            { role: "MANAGER", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
            {
              role: "OFFICIAL",
              auth: [
                "approver",
                "inbox_viewer",
                "outbox_viewer",
                "handle_filter_document_task",
              ],
            },
          ],
        },
        directoryActivated: 0,
        dirPreferences: { btbEmail: "elkenziamine@gmail.com" },
        directBilling: true,
        blogActivated: 1,
        mediaActivated: 0,
        forumActivated: 0,
        webtoolsActivated: 0,
        eventActivated: 0,
        paymentActivated: 0,
        dataActivated: 0,
        surveyActivated: 0,
        fluxActivated: 1,
        chatActivated: 1,
        socialNetworks: [],
        emailingActivated: 0,
        appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
        smsCredit: 0,
        profitMargin: 0,
        gdprAlertEnabled: 0,
        portalClientActivated: 0,
        portalOfficialActivated: 0,
        organizationSettingsId: 74,
        appsState: [
          {
            code: "blog",
            name: { fr: "Blog", en: "Blog", nl: "Blog" },
            url: "https://blog.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/blog.png",
            activated: true,
          },
          {
            code: "media",
            name: { fr: "Media", en: "Media", nl: "Media" },
            url: "https://media.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/media.png",
            activated: false,
          },
          {
            code: "forum",
            name: { fr: "Forum", en: "Forum", nl: "Forum" },
            url: "https://forum.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/forum.png",
            activated: false,
          },
          {
            code: "emailing",
            name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
            url: "https://sending.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
            activated: false,
          },
          {
            code: "ebox",
            name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
            url: "https://sending.rc2.tamtam.pro/e_box",
            icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
            activated: true,
          },
          {
            code: "sms",
            name: { fr: "SMS", en: "SMS", nl: "SMS" },
            url: "https://sending.rc2.tamtam.pro/smsCampaigns",
            icon: "https://s3.tamtam.pro/v2/apps/sms.png",
            activated: false,
          },
          {
            code: "talk",
            name: { fr: "Talk", en: "Talk", nl: "Talk" },
            url: "https://talk.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/talk.png",
            activated: true,
          },
          {
            code: "data",
            name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
            url: "https://accounting.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
            activated: false,
          },
          {
            code: "webtools",
            name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
            url: "https://webtool.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
            activated: false,
          },
          {
            code: "survey",
            name: { fr: "Survey", en: "Survey", nl: "Survey" },
            url: "https://survey.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/survey.png",
            activated: false,
          },
          {
            code: "event",
            name: { fr: "Event", en: "Event", nl: "Event" },
            url: "https://event.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/event.png",
            activated: false,
          },
          {
            code: "directory",
            name: {
              fr: "Directory (HQ)",
              en: "Directory (HQ)",
              nl: "Directory (HQ)",
            },
            url: "https://rc2.tamtam.pro/folders",
            icon: "https://s3.tamtam.pro/v2/apps/directory.png",
            activated: false,
          },
          {
            code: "payment",
            name: { fr: "Payment", en: "Payment", nl: "Payment" },
            url: "https://payment.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/payment.png",
            activated: false,
          },
          {
            code: "portal",
            name: { fr: "Portal", en: "Portal", nl: "Portal" },
            url: "https://portal.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/portal.png",
            activated: false,
          },
        ],
        startDate: null,
        url: "tamtam-pro",
        blogs: [
          {
            blogId: 10,
            id: 48,
            role: "REDACTOR",
            mandated: false,
            preferences: [],
          },
        ],
        mediaSettings: {
          preferences: [],
          roles: {
            id: 5,
            preferences: { languages: "FR" },
            imageRole: "CHIEF_EDITOR",
            pdfRole: "CHIEF_EDITOR",
            pptRole: "CHIEF_EDITOR",
            videoRole: "CHIEF_EDITOR",
          },
        },
      },
      {
        id: 83,
        uen: "0000002018",
        name: "Tamtam",
        abbreviation: "",
        btbPreferences: {
          authorizations: [
            { role: "MANAGER", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
            {
              role: "OFFICIAL",
              auth: [
                "approver",
                "inbox_viewer",
                "outbox_viewer",
                "handle_filter_document_task",
              ],
            },
          ],
        },
        directoryActivated: 0,
        dirPreferences: { btbEmail: "ramrami.mohamed.4@gmail.com" },
        directBilling: true,
        blogActivated: 0,
        mediaActivated: 0,
        forumActivated: 0,
        webtoolsActivated: 0,
        eventActivated: 0,
        paymentActivated: 0,
        dataActivated: 0,
        surveyActivated: 0,
        fluxActivated: 0,
        chatActivated: 1,
        socialNetworks: [],
        emailingActivated: 0,
        appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
        smsCredit: 0,
        profitMargin: 0,
        gdprAlertEnabled: 0,
        portalClientActivated: 0,
        portalOfficialActivated: 0,
        organizationSettingsId: 81,
        appsState: [
          {
            code: "blog",
            name: { fr: "Blog", en: "Blog", nl: "Blog" },
            url: "https://blog.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/blog.png",
            activated: false,
          },
          {
            code: "media",
            name: { fr: "Media", en: "Media", nl: "Media" },
            url: "https://media.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/media.png",
            activated: false,
          },
          {
            code: "forum",
            name: { fr: "Forum", en: "Forum", nl: "Forum" },
            url: "https://forum.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/forum.png",
            activated: false,
          },
          {
            code: "emailing",
            name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
            url: "https://sending.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
            activated: false,
          },
          {
            code: "ebox",
            name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
            url: "https://sending.rc2.tamtam.pro/e_box",
            icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
            activated: true,
          },
          {
            code: "sms",
            name: { fr: "SMS", en: "SMS", nl: "SMS" },
            url: "https://sending.rc2.tamtam.pro/smsCampaigns",
            icon: "https://s3.tamtam.pro/v2/apps/sms.png",
            activated: false,
          },
          {
            code: "talk",
            name: { fr: "Talk", en: "Talk", nl: "Talk" },
            url: "https://talk.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/talk.png",
            activated: true,
          },
          {
            code: "data",
            name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
            url: "https://accounting.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
            activated: false,
          },
          {
            code: "webtools",
            name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
            url: "https://webtool.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
            activated: false,
          },
          {
            code: "survey",
            name: { fr: "Survey", en: "Survey", nl: "Survey" },
            url: "https://survey.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/survey.png",
            activated: false,
          },
          {
            code: "event",
            name: { fr: "Event", en: "Event", nl: "Event" },
            url: "https://event.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/event.png",
            activated: false,
          },
          {
            code: "directory",
            name: {
              fr: "Directory (HQ)",
              en: "Directory (HQ)",
              nl: "Directory (HQ)",
            },
            url: "https://rc2.tamtam.pro/folders",
            icon: "https://s3.tamtam.pro/v2/apps/directory.png",
            activated: false,
          },
          {
            code: "payment",
            name: { fr: "Payment", en: "Payment", nl: "Payment" },
            url: "https://payment.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/payment.png",
            activated: false,
          },
          {
            code: "portal",
            name: { fr: "Portal", en: "Portal", nl: "Portal" },
            url: "https://portal.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/portal.png",
            activated: false,
          },
        ],
        startDate: null,
        url: "tamtam",
        mediaSettings: { preferences: [] },
      },
      {
        id: 8,
        name:
          "Instituut van de Accountants en de Belastingconsulenten - Institut des Experts-comptables et des Conseils fiscaux",
        abbreviation: "IEC-IAB",
        avatarWebPath:
          "storage/media/IMAGE/5401/AVATAR_d2ed4d5412bae00850a3be09cf55d08f3a23d7a0.png",
        avatarUrl:
          "https://s3.tamtam.pro/local/storage/media/IMAGE/5401/AVATAR_d2ed4d5412bae00850a3be09cf55d08f3a23d7a0.png",
        btbPreferences: {
          authorizations: [
            { role: "MANAGER", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
            { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
            {
              role: "OFFICIAL",
              auth: [
                "approver",
                "inbox_viewer",
                "outbox_viewer",
                "handle_filter_document_task",
              ],
            },
          ],
        },
        directoryActivated: 1,
        dirPreferences: { btbEmail: "emmanuel.degreve+bvn@degandpartners.com" },
        directBilling: true,
        blogActivated: 1,
        mediaActivated: 0,
        forumActivated: 0,
        webtoolsActivated: 0,
        eventActivated: 0,
        paymentActivated: 0,
        dataActivated: 0,
        surveyActivated: 0,
        fluxActivated: 1,
        chatActivated: 0,
        socialNetworks: [],
        emailingPreferences: {
          from_email: "communication@iec-iab.be",
          base_url: "http://tamtam.pro/emailsIec/",
          from_name: "IEC - IAB",
          cs_app_scope: "INTRA_CROSS",
          cs_default_scope: "INTRA_CROSS",
        },
        emailingTestingPreferences: {
          approversEmailsIds: [25204, 21545, 35210],
          autoSend: false,
          mandatoryTest: false,
          minApprover: 0,
        },
        emailingActivated: 1,
        appsValidationStatus: { wtb: [], btb: ["iban"], btbfiles: [] },
        smsCredit: 0,
        profitMargin: 0,
        gdprAlertEnabled: 0,
        portalClientActivated: 0,
        portalOfficialActivated: 0,
        organizationSettingsId: 6,
        appsState: [
          {
            code: "blog",
            name: { fr: "Blog", en: "Blog", nl: "Blog" },
            url: "https://blog.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/blog.png",
            activated: true,
          },
          {
            code: "media",
            name: { fr: "Media", en: "Media", nl: "Media" },
            url: "https://media.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/media.png",
            activated: false,
          },
          {
            code: "forum",
            name: { fr: "Forum", en: "Forum", nl: "Forum" },
            url: "https://forum.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/forum.png",
            activated: false,
          },
          {
            code: "emailing",
            name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
            url: "https://sending.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
            activated: true,
          },
          {
            code: "ebox",
            name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
            url: "https://sending.rc2.tamtam.pro/e_box",
            icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
            activated: true,
          },
          {
            code: "sms",
            name: { fr: "SMS", en: "SMS", nl: "SMS" },
            url: "https://sending.rc2.tamtam.pro/smsCampaigns",
            icon: "https://s3.tamtam.pro/v2/apps/sms.png",
            activated: true,
          },
          {
            code: "talk",
            name: { fr: "Talk", en: "Talk", nl: "Talk" },
            url: "https://talk.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/talk.png",
            activated: false,
          },
          {
            code: "data",
            name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
            url: "https://accounting.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
            activated: false,
          },
          {
            code: "webtools",
            name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
            url: "https://webtool.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
            activated: false,
          },
          {
            code: "survey",
            name: { fr: "Survey", en: "Survey", nl: "Survey" },
            url: "https://survey.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/survey.png",
            activated: false,
          },
          {
            code: "event",
            name: { fr: "Event", en: "Event", nl: "Event" },
            url: "https://event.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/event.png",
            activated: false,
          },
          {
            code: "directory",
            name: {
              fr: "Directory (HQ)",
              en: "Directory (HQ)",
              nl: "Directory (HQ)",
            },
            url: "https://rc2.tamtam.pro/folders",
            icon: "https://s3.tamtam.pro/v2/apps/directory.png",
            activated: true,
          },
          {
            code: "payment",
            name: { fr: "Payment", en: "Payment", nl: "Payment" },
            url: "https://payment.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/payment.png",
            activated: false,
          },
          {
            code: "portal",
            name: { fr: "Portal", en: "Portal", nl: "Portal" },
            url: "https://portal.rc2.tamtam.pro/",
            icon: "https://s3.tamtam.pro/v2/apps/portal.png",
            activated: false,
          },
        ],
        startDate: null,
        url:
          "instituut-van-de-accountants-en-de-belastingconsulenten-institut-des-experts-comptables-et-des-conseils-fiscaux",
        hasFiduciariesAdmin: true,
        blogs: [
          {
            blogId: 6,
            id: 33,
            role: "CHIEF_EDITOR",
            preferences: {
              allowCreateTags: 1,
              allowedLanguages: ["fr"],
            },
            mandated: false,
          },
        ],
        mediaSettings: { preferences: [] },
      },
    ],
    url: "emmanuel-degreve",
    contactSocialNetworks: {
      facebook: {
        id: 568543643,
        username: "Emmanuel Degrève",
        publicProfileUrl: null,
      },
      twitter: {
        id: 175482549,
        username: "emmanueldegreve",
        publicProfileUrl: null,
      },
      linkedin: {
        id: "dnuRIWeubQ",
        username: "Emmanuel Degrève",
        publicProfileUrl:
          "https://www.linkedin.com/in/emmanuel-degr%C3%A8ve-b2a6235",
      },
    },
  },
  error: null,
  loggedAs: "MEMBER",
  loggedAsPost: "LEGAL_REPRESENTATIVE",
  navCommunity: {
    id: 9,
    uen: "0899167234",
    name: "Forum For The Future",
    abbreviation: "F.F.F.",
    avatarWebPath:
      "storage/media/IMAGE/5400/AVATAR_74ad9ed232db222831d9dd2cb0bae95fcb64eeb0.png",
    avatarUrl:
      "https://s3.tamtam.pro/local/storage/media/IMAGE/5400/AVATAR_74ad9ed232db222831d9dd2cb0bae95fcb64eeb0.png",
    btbPreferences: {
      authorizations: [
        { role: "MANAGER", auth: ["*"] },
        { role: "LEGAL_REPRESENTATIVE_ADMIN", auth: ["*"] },
        { role: "LEGAL_REPRESENTATIVE_MANAGER", auth: ["*"] },
        {
          role: "OFFICIAL",
          auth: [
            "approver",
            "inbox_viewer",
            "outbox_viewer",
            "handle_filter_document_task",
          ],
        },
      ],
    },
    directoryActivated: 1,
    dirPreferences: {
      btbEmail: "emmanuel.degreve@degandpartners.com",
      appliedChannelsStatus: [
        { id: "BILLTOBOX_INIT_ID", name: "billtobox", status: "deactivated" },
        {
          id: "BILLTOBOXFILES_INIT_ID",
          name: "billtoboxfiles",
          status: "activated",
        },
      ],
    },
    directBilling: true,
    blogActivated: 1,
    mediaActivated: 1,
    forumActivated: 1,
    webtoolsActivated: 1,
    eventActivated: 1,
    paymentActivated: 0,
    dataActivated: 0,
    surveyActivated: 1,
    fluxActivated: 1,
    chatActivated: 1,
    socialNetworks: {
      twitter: {
        624465904: {
          id: "624465904",
          username: "DegandPartners",
          profile_picture:
            "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69_normal.jpeg",
          profile_picture_original:
            "http://pbs.twimg.com/profile_images/557557639333154817/njB7Cr69.jpeg",
          profile_banner:
            "https://pbs.twimg.com/profile_banners/624465904/1421767061/600x200",
          accesstoken: {
            oauth_token: "624465904-LHB2jXz5oCm3KDaH0NNkUbmvHTKFjVKzokVgQ554",
            oauth_token_secret: "i6sJKCHIFpI7o8HOhRL1p4pg9QYKT8vP7foQgrozsUMQy",
          },
        },
      },
    },
    emailingPreferences: {
      cs_app_scope: "EXTRA_CROSS",
      cs_default_scope: "EXTRA_CROSS",
    },
    emailingTestingPreferences: {
      approversEmailsIds: [],
      autoSend: false,
      mandatoryTest: false,
      minApprover: 0,
    },
    emailingActivated: 1,
    appsValidationStatus: { wtb: [], btb: [], btbfiles: [] },
    mediaPreferences: {
      languages: "FR,NL",
      generalTypes: "VIDEO,PDF,PPT",
      publicProfile: "1",
      defaultData: "{}",
    },
    hubPreferences: {
      layout_settings: [
        { sectionId: "event", order: 2, enabled: true },
        { sectionId: "forum", order: 4, enabled: false },
        { sectionId: "media", order: 3, enabled: true },
        { sectionId: "blog", order: 1, enabled: true },
      ],
      drawers: [
        {
          app: "BLOG",
          label: "Blog",
          url: "http://local.blog.tamtam.pro",
          enabled: true,
        },
        {
          app: "EVENT",
          label: "Event",
          url: "http://local.event.tamtam.pro",
          enabled: true,
        },
        {
          app: "MEDIA",
          label: "Media",
          url: "http://local.media.tamtam.pro:3333",
          enabled: true,
        },
        {
          app: "FORUM",
          label: "Forum",
          url: "http://local.forum.tamtam.pro:3001",
          enabled: true,
        },
      ],
    },
    smsCredit: 0,
    profitMargin: 0,
    defaultMemberAuthorisationMode: "",
    defaultProspectAuthorisationMode: "",
    gdprAlertEnabled: 0,
    csGeneralScope: "EXTRA_CROSS",
    portalClientActivated: 1,
    portalOfficialActivated: 1,
    organizationSettingsId: 4,
    appsState: [
      {
        code: "blog",
        name: { fr: "Blog", en: "Blog", nl: "Blog" },
        url: "https://blog.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/blog.png",
        activated: true,
      },
      {
        code: "media",
        name: { fr: "Media", en: "Media", nl: "Media" },
        url: "https://media.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/media.png",
        activated: true,
      },
      {
        code: "forum",
        name: { fr: "Forum", en: "Forum", nl: "Forum" },
        url: "https://forum.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/forum.png",
        activated: true,
      },
      {
        code: "emailing",
        name: { fr: "Emailing", en: "Emailing", nl: "Emailing" },
        url: "https://sending.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/emailing.png",
        activated: true,
      },
      {
        code: "ebox",
        name: { fr: "E-Box", en: "E-Box", nl: "E-Box" },
        url: "https://sending.rc2.tamtam.pro/e_box",
        icon: "https://s3.tamtam.pro/v2/apps/ebox.png",
        activated: true,
      },
      {
        code: "sms",
        name: { fr: "SMS", en: "SMS", nl: "SMS" },
        url: "https://sending.rc2.tamtam.pro/smsCampaigns",
        icon: "https://s3.tamtam.pro/v2/apps/sms.png",
        activated: true,
      },
      {
        code: "talk",
        name: { fr: "Talk", en: "Talk", nl: "Talk" },
        url: "https://talk.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/talk.png",
        activated: true,
      },
      {
        code: "data",
        name: { fr: "Accounting", en: "Accounting", nl: "Accounting" },
        url: "https://accounting.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/accounting.png",
        activated: false,
      },
      {
        code: "webtools",
        name: { fr: "Webtools", en: "Webtools", nl: "Webtools" },
        url: "https://webtool.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/webtools.png",
        activated: true,
      },
      {
        code: "survey",
        name: { fr: "Survey", en: "Survey", nl: "Survey" },
        url: "https://survey.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/survey.png",
        activated: true,
      },
      {
        code: "event",
        name: { fr: "Event", en: "Event", nl: "Event" },
        url: "https://event.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/event.png",
        activated: true,
      },
      {
        code: "directory",
        name: {
          fr: "Directory (HQ)",
          en: "Directory (HQ)",
          nl: "Directory (HQ)",
        },
        url: "https://rc2.tamtam.pro/folders",
        icon: "https://s3.tamtam.pro/v2/apps/directory.png",
        activated: true,
      },
      {
        code: "payment",
        name: { fr: "Payment", en: "Payment", nl: "Payment" },
        url: "https://payment.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/payment.png",
        activated: false,
      },
      {
        code: "portal",
        name: { fr: "Portal", en: "Portal", nl: "Portal" },
        url: "https://portal.rc2.tamtam.pro/",
        icon: "https://s3.tamtam.pro/v2/apps/portal.png",
        activated: true,
      },
    ],
    startDate: null,
    url: "deg-and-partners-consulting-company",
    blogs: [
      {
        blogId: 8,
        id: 26,
        role: "CHIEF_EDITOR",
        preferences: {
          allowCreateTags: 1,
          allowedLanguages: ["en", "fr", "nl"],
        },
        mandated: false,
      },
    ],
    mediaSettings: {
      preferences: {
        languages: "FR,NL",
        generalTypes: "IMAGE,VIDEO,PPT",
        publicProfile: "1",
        defaultData: "{}",
      },
      roles: {
        id: 4,
        preferences: { languages: "FR,EN,NL" },
        imageRole: "CHIEF_EDITOR",
        pdfRole: "CHIEF_EDITOR",
        pptRole: "CHIEF_EDITOR",
        videoRole: "",
      },
    },
  },
};
